title: "Canva MCP Integration Guide"
description: "A complete guide to integrating Canva with AI models via the Model Context Protocol (MCP)"
baseurl: ""
url: "https://rinsanom.github.io/MCP-with-Canva-Config/"
repository: "rinsanom/mcp_config"

remote_theme: just-the-docs/just-the-docs # or remove for default Minima


nav_enabled: true


plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown processor
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections for docs
collections:
  docs:
    output: true
    permalink: /:collection/:name/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# SEO / Social
author: "Rin Sanom"

color_scheme: light
search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2026 Your Organisation. Distributed under an MIT licence."
